'use strict';
const C=NextCup,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const prefix='next-cup:v04:',recordsKey=prefix+'records';
let filter='all',lastComparison=null,requestEdit=null,ideaEdit=null,toastTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;toastTimer=setTimeout(()=>$('#toast').textContent='',5500);}
function readRecords(){try{const raw=localStorage.getItem(recordsKey);if(!raw)return[];const records=JSON.parse(raw);if(!Array.isArray(records)||!records.every(C.isRecord))throw Error('invalid');return records;}catch{throw Error('저장 기록을 읽을 수 없습니다.');}}
function writeRecords(records){try{localStorage.setItem(recordsKey,JSON.stringify(records));return true;}catch{return false;}}
// All storage failures are explicit; damaged records are never replaced silently.
function storageFailure(){toast('기록을 읽거나 저장할 수 없습니다. 기존 기록은 덮어쓰지 않았습니다. 브라우저 저장 설정을 확인해 주세요.');}
function saveRecord(type,payload,editId=null){const error=C.validate(type,payload);if(error){toast(error);return false;}let records;try{records=readRecords();}catch{storageFailure();return false;}const duplicate=records.find(r=>r.id!==editId&&C.signature(r.type,r.payload)===C.signature(type,payload));if(duplicate){toast('같은 내용이 이미 내 보관함에 있습니다.');return false;}
 if(editId&&!records.some(r=>r.id===editId&&r.type===type)){toast('수정할 기록을 찾지 못했습니다. 내 보관함을 다시 확인해 주세요.');return false;}
 const old=records.find(r=>r.id===editId);const record={id:old?.id||crypto.randomUUID(),type,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),payload};
 const next=old?records.map(r=>r.id===editId?record:r):[record,...records];if(!writeRecords(next)){storageFailure();return false;}filter='all';$$('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.filter==='all')));renderCollection();toast(old?'수정한 내용을 이 기기에 저장했습니다. 외부 전송은 하지 않았습니다.':'이 기기에 저장했습니다. 스타벅스에 전송되지 않았습니다.');return true;
}
function capture(form){const values={};for(const el of form.elements){if(!el.name)continue;if(el.type==='checkbox'){values[el.name]??=[];if(el.checked)values[el.name].push(el.value);}else values[el.name]=el.value.trim();}return values;}
function fill(form,values){for(const el of form.elements){if(!el.name||!Object.hasOwn(values,el.name))continue;const v=values[el.name];if(el.type==='checkbox')el.checked=Array.isArray(v)&&v.includes(el.value);else if(typeof v==='string'&&v.length<=1000)el.value=v;}}
function draft(form,key,editId){try{localStorage.setItem(prefix+key,JSON.stringify({values:capture(form),editId}));}catch{toast('임시 보관에 실패했습니다. 작성 내용은 화면에 남아 있습니다.');}}
function restoreDraft(form,key){try{const raw=localStorage.getItem(prefix+key);if(!raw)return null;const d=JSON.parse(raw);if(!d||typeof d.values!=='object'||!d.values||Array.isArray(d.values))throw Error();fill(form,d.values);return typeof d.editId==='string'?d.editId:null;}catch{toast('임시 작성 내용을 복원하지 못했습니다. 저장된 메뉴 기록은 그대로 두었습니다.');return null;}}
const requestForm=$('#request-form'),ideaForm=$('#studio-form');
requestEdit=restoreDraft(requestForm,'request-draft');ideaEdit=restoreDraft(ideaForm,'idea-draft');
function requestKind(){const local=$('#request-kind').value==='local';$('#local-menu-field').hidden=!local;$('#local-menu').required=local;}
function preview(){const p=capture(ideaForm);$('#preview-name').textContent=p.title||'아직 이름 없는, 나의 다음 한 잔.';$('#preview-components').textContent=[C.bases[p.base],(p.ingredient||[]).map(i=>C.ingredients[i]).join(' + ')||'재료를 골라주세요',C.textures[p.texture]].filter(Boolean).join(' ,  ');$('#preview-story').textContent=p.story||'좋아하는 맛에서 시작해 보세요.';}
function editState(){
 for(const [form,id,type] of [[requestForm,requestEdit,'request'],[ideaForm,ideaEdit,'idea']]){
  let panel=form.querySelector('.edit-notice');if(!panel){panel=document.createElement('div');panel.className='notice-box edit-notice';form.prepend(panel);}
  panel.hidden=!id;panel.innerHTML='<strong>저장한 기록을 수정하고 있어요.</strong><br><button class="outline small" type="button" data-cancel-edit="'+type+'">수정 취소하고 새로 작성</button>';
 }
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-cancel-edit]');if(!b)return;if(b.dataset.cancelEdit==='request'){requestEdit=null;requestForm.reset();requestKind();draft(requestForm,'request-draft',null);}else{ideaEdit=null;ideaForm.reset();preview();draft(ideaForm,'idea-draft',null);}editState();toast('수정을 취소했습니다. 기존에 저장한 기록은 유지됩니다.');});
requestKind();preview();editState();
requestForm.addEventListener('input',()=>{requestKind();draft(requestForm,'request-draft',requestEdit);$('#request-error').textContent='';});
ideaForm.addEventListener('input',()=>{preview();draft(ideaForm,'idea-draft',ideaEdit);$('#studio-error').textContent='';});
requestForm.addEventListener('submit',event=>{event.preventDefault();const p=capture(requestForm);if(p.kind==='return')p.localMenu='';const error=C.validate('request',p);$('#request-error').textContent=error;if(error)return;if(saveRecord('request',p,requestEdit)){requestEdit=null;requestForm.reset();requestKind();draft(requestForm,'request-draft',null);location.hash='collection';}});
ideaForm.addEventListener('submit',event=>{event.preventDefault();const p=capture(ideaForm);p.ingredients=p.ingredient||[];delete p.ingredient;const error=C.validate('idea',p);$('#studio-error').textContent=error;if(error)return;if(saveRecord('idea',p,ideaEdit)){ideaEdit=null;ideaForm.reset();preview();draft(ideaForm,'idea-draft',null);location.hash='collection';}});
window.NextCupAIState={dislikes:[]};
function tasteInput(){return{tags:$$('[name=taste]:checked').map(el=>el.value),essential:$('#essential').checked,store:$('#store').value,dislikes:window.NextCupAIState.dislikes};}
async function compare(){const p=tasteInput();const button=$('#taste-form button[type=submit]');button.disabled=true;lastComparison=null;let result;try{const response=await fetch('/api/recommend',{method:'POST',headers:{'Content-Type':'application/json','X-Next-Cup':'1'},body:JSON.stringify(p)});result=await response.json();if(!response.ok)throw Error(result.error);if(JSON.stringify(tasteInput())!==JSON.stringify(p)){toast('비교 중 조건이 바뀌었습니다. 다시 비교해 주세요.');return;}}catch(e){$('#comparison-title').textContent='조건을 확인해 주세요.';$('#results').textContent=e.message||'서버 연결에 실패했습니다.';return;}finally{button.disabled=false;}lastComparison={input:p,result};const actions='<div class="result-actions"><a class="button" href="#request">이 메뉴, 다시 만나고 싶어요 ↗</a><a class="outline" href="#studio">새로운 메뉴 제안</a></div>';
 if(result.status==='unknown'){$('#comparison-title').textContent='판매 정보를 먼저 확인해야 해요.';$('#results').innerHTML='<p>이 매장은 정보가 없어 대안을 제안하지 않았습니다. 다른 매장 조건을 선택하거나 메뉴 요청을 남겨주세요.</p>'+actions;}
 else if(result.status==='clarify'){$('#comparison-title').textContent='좋아했던 느낌을 하나 골라주세요.';$('#results').innerHTML='<p>쌀 풍미, 크림감, 차갑게 갈린 질감, 토핑 중 기억나는 것을 선택해 주세요.</p>';}
 else if(result.status==='empty'){$('#comparison-title').textContent=p.essential?'쌀의 구수함, 대신할 후보가 없어요.':'선택한 감각을 이을 후보가 없어요.';$('#results').innerHTML='<span class="badge">현재 시연 후보 안에서 추천 보류</span><p>마음에 안 드는 대안을 고를 필요는 없어요. 원래 메뉴를 다시 만나고 싶은 이유를 기록해 볼까요?</p><p class="fine">다른 감각만 비교하려면 왼쪽의 ‘쌀 풍미만큼은 꼭 유지’ 선택을 직접 해제해 주세요. 실제 전체 메뉴에 대안이 없다는 뜻은 아닙니다.</p>'+actions;}
 else if(result.status==='partial'){$('#comparison-title').textContent='같은 맛이 아닌, 일부 취향의 연결.';$('#results').innerHTML='<span class="badge">가상 매장 ,  맛 태그는 설계 가정</span><p>아래 후보에는 쌀 풍미가 없습니다. 이름만으로 맛의 유사성을 보장하지 않으며, 실제 판매 여부도 확인해야 합니다.</p>'+result.candidates.map(d=>`<article class="result-card"><h4>${esc(d.name)}</h4><p><strong>이어볼 감각</strong> ,  ${d.shared.map(t=>C.labels[t]).join(', ')}</p><p><strong>달라지는 점</strong> ,  ${esc(d.difference)}</p><button type="button" class="outline" data-save="${d.id}">다음 잔 후보 저장</button></article>`).join('')+actions;}
 else{$('#comparison-title').textContent='입력 조건을 다시 확인해 주세요.';$('#results').textContent='선택한 조건을 읽지 못했습니다.';}
 const evidence=document.createElement('details');evidence.innerHTML='<summary>처리 과정과 메뉴 자료 확인</summary><ol>'+result.trace.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ol>'+result.sources.map(s=>'<p class="fine"><a target="_blank" rel="noreferrer" href="'+esc(s.url)+'">'+esc(C.drinks.find(d=>d.id===s.id)?.name)+' 자료 ↗</a><br>'+esc(s.scope)+' ,  확인 '+esc(s.checked)+'</p>').join('');$('#results').append(evidence);
}
$('#taste-form').addEventListener('submit',e=>{e.preventDefault();compare();});
$('#taste-form').addEventListener('change',()=>{lastComparison=null;$('#comparison-title').textContent='취향이 달라졌네요. 다시 비교해 볼까요?';$('#results').innerHTML='<p>바뀐 조건으로 ‘이어갈 수 있는 취향 찾기’를 눌러주세요. 이전 후보는 저장되지 않습니다.</p>';});
$('#results').addEventListener('click',e=>{const button=e.target.closest('[data-save]');if(!button||!lastComparison)return;const id=button.dataset.save;if(lastComparison.result.candidates.some(d=>d.id===id))saveRecord('candidate',{...lastComparison.input,drinkId:id,feedback:'pending'});});
function renderCollection(){let records;try{records=readRecords();}catch{$('#collection-content').innerHTML='<div class="empty"><h2>기록을 읽지 못했어요.</h2><p>기존 데이터는 보존했습니다. 브라우저 저장 설정이나 기록 형식을 확인해야 합니다.</p></div>';return;}
 const selected=records.filter(r=>filter==='all'||r.type===filter);if(!selected.length){$('#collection-content').innerHTML='<div class="empty"><p class="eyebrow">YOUR TASTE STARTS HERE</p><h2>아직 담긴 이야기가 없어요.</h2><p>그리운 이유 하나가 다음 메뉴의 시작이 될 수 있어요.</p><a class="button" href="#request">첫 메뉴 요청 남기기 ↗</a></div>';return;}
 $('#collection-content').innerHTML=selected.map(r=>{const p=r.payload;const type={request:'메뉴 요청 ,  미전송',idea:'내 메뉴 아이디어 ,  미전송',candidate:'부분 대안 ,  판매 상태 미확인'}[r.type];let body='';
 if(r.type==='request'){body=`<h3>${esc(p.kind==='return'?'이천 햅쌀 크림 프라푸치노':p.localMenu)}</h3><p>${esc(p.reason)}</p><p><strong>꼭 지킬 것</strong> ,  ${esc(p.keep)}</p>${p.change?`<p><strong>달라져도 괜찮은 것</strong> ,  ${esc(p.change)}</p>`:''}`;}
 if(r.type==='idea'){body=`<h3>${esc(p.title)}</h3><p>${esc(C.bases[p.base])} ,  ${p.ingredients.map(i=>C.ingredients[i]).join(' + ')} ,  ${C.textures[p.texture]}</p><p>${esc(p.story)}</p><p class="fine">실제 주문 레시피가 아닌 제안입니다. 제조, 영양, 알레르기 검증 전입니다.</p>`;}
 if(r.type==='candidate'){const d=C.drinks.find(d=>d.id===p.drinkId);body=`<h3>${esc(d.name)}</h3><p>${esc(d.difference)}</p><p class="fine">가상 매장 ${p.store==='all'?'A':'B'} ,  ${p.tags.map(t=>C.labels[t]).join(', ')}</p><div class="feedback"><label for="feedback-${r.id}">실제로 마셔본 느낌</label><select id="feedback-${r.id}" data-feedback="${r.id}">${Object.entries({pending:'아직 마시지 않았어요',liked:'이 취향은 이어졌어요',different:'기대한 느낌과 달라요',tooSweet:'너무 달게 느껴져요'}).map(([v,t])=>`<option value="${v}" ${p.feedback===v?'selected':''}>${t}</option>`).join('')}</select></div>`;}
 return`<article class="card"><span class="status-chip">${type}</span>${body}<p class="fine">${new Date(r.createdAt).toLocaleDateString('ko-KR')} ,  내 브라우저 저장</p>${r.type!=='candidate'?`<button type="button" class="outline" data-edit="${r.id}">내용 수정하기</button>`:''}</article>`;}).join('');
}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));renderCollection();}));
$('#collection-content').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(!b)return;let records;try{records=readRecords();}catch{storageFailure();return;}const r=records.find(r=>r.id===b.dataset.edit);if(!r)return;if(r.type==='request'){fill(requestForm,r.payload);requestEdit=r.id;requestKind();draft(requestForm,'request-draft',r.id);location.hash='request';}else{fill(ideaForm,{...r.payload,ingredient:r.payload.ingredients});ideaEdit=r.id;preview();draft(ideaForm,'idea-draft',r.id);location.hash='studio';}toast('저장된 기록을 수정하는 중입니다. 저장 버튼을 누르면 이 기록이 갱신됩니다.');});
$('#collection-content').addEventListener('change',e=>{if(!e.target.matches('[data-feedback]'))return;let records;try{records=readRecords();}catch{storageFailure();return;}const r=records.find(r=>r.id===e.target.dataset.feedback);if(r)saveRecord('candidate',{...r.payload,feedback:e.target.value},r.id);});
$('#export').addEventListener('click',()=>{try{const records=readRecords();if(!records.length){toast('내려받을 기록이 아직 없습니다.');return;}const blob=new Blob([JSON.stringify({version:4,notice:'개인 시제품 기록. 스타벅스에 전송되지 않음.',records},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='next-cup-records-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('파일 내려받기를 요청했습니다. 브라우저의 다운로드 내역을 확인해 주세요.');}catch{storageFailure();}});
function route(initial=false){const hash=location.hash.slice(1)||'discover';if(hash==='main'){$('#main').focus();return;}const page=hash==='finder'?'discover':['discover','request','studio','collection','notes','community','research'].includes(hash)?hash:'discover';$$('.view').forEach(v=>v.hidden=v.id!==page);$$('.header a').forEach(a=>{if(a.getAttribute('href')==='#'+page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});editState();if(page==='collection')renderCollection();if(hash==='finder'){$('#finder').scrollIntoView();}else if(!initial){window.scrollTo(0,0);$('#main').focus({preventScroll:true});}}
window.addEventListener('hashchange',()=>route());window.addEventListener('storage',e=>{if(e.key===recordsKey)renderCollection();});route(true);renderCollection();
