import {chromium} from 'playwright';
import path from 'node:path';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const root=path.resolve('runtime/browser-check');
await fs.mkdir(path.join(root,'qa'),{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
await page.goto('http://127.0.0.1:4322/#discover');
await page.locator('[name=taste][value=rice]').check();
await page.locator('[name=taste][value=ice]').check();
await page.locator('#rice-requirement').selectOption('yes');
await page.locator('#taste-form button[type=submit]').click();
await page.locator('#comparison-title').filter({hasText:'대신할 후보가 없어요'}).waitFor();
const results=await page.locator('#results').boundingBox(),card=await page.locator('.comparison').boundingBox();
const scroll=await page.evaluate(()=>({x:scrollX,y:scrollY}));
await page.screenshot({path:path.join(root,'qa/07-hold-detail.png'),fullPage:true,clip:{x:card.x+scroll.x,y:card.y+scroll.y,width:card.width,height:results.y+results.height-card.y+24}});
await page.locator('[data-unmet]').click();
await page.locator('#request-form button[type=submit]').click();
await page.waitForURL('**/#collection');
await page.locator('#collection-content .card').first().screenshot({path:path.join(root,'qa/08-saved-detail.png')});
await page.goto('http://127.0.0.1:4322/#discover');
await page.locator('[name=taste][value=rice]').uncheck();
await page.locator('[name=taste][value=ice]').check();
await page.locator('[name=avoid][value=coffee]').check();
await page.locator('#rice-requirement').selectOption('no');
await page.locator('#taste-form button[type=submit]').click();
await page.locator('.result-card h4').filter({hasText:'초콜릿'}).waitFor();
await page.locator('.result-card').screenshot({path:path.join(root,'qa/09-chocolate-detail.png')});
await page.locator('[name=taste][value=ice]').uncheck();
await page.locator('[name=avoid][value=coffee]').uncheck();
await page.locator('[name=taste][value=vanilla]').check();
await page.locator('#taste-form button[type=submit]').click();
await page.locator('.result-card h4').filter({hasText:'바닐라'}).waitFor();
await page.locator('.result-card').screenshot({path:path.join(root,'qa/10-vanilla-detail.png')});
await page.locator('[name=taste][value=vanilla]').uncheck();
await page.locator('#rice-requirement').selectOption('yes');
await page.locator('#taste-form button[type=submit]').click();
await page.locator('#comparison-title').filter({hasText:'대신할 후보가 없어요'}).waitFor();
assert.equal(await page.locator('.result-card').count(),0);
await page.setViewportSize({width:375,height:900});await page.locator('#taste-form').scrollIntoViewIfNeeded();
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:path.join(root,'qa/11-mobile.png')});
await fs.writeFile(path.join(root,'qa/final-smoke.json'),JSON.stringify({method:'synthetic manual browser flow',aiCalls:0,emptyLikesRequiredRice:'hold',riceRequestStored:true,chocolate:true,vanilla:true,mobileOverflow:false}));
await browser.close();console.log('manual final flow verified');
