const test=require('node:test'),assert=require('node:assert/strict');const {createApp}=require('../app/server.cjs');const {createAI,checkTaste,checkSummary,pii}=require('../app/ai.cjs');const C=require('../app/core.js');
const taste={likes:['rice','cream'],dislikes:[],essentialRice:'yes',understanding:'쌀과 크림감을 좋아합니다.',question:'바삭한 식감도 중요했나요?',evidence:[{tag:'rice',polarity:'like',quote:'쌀과 크림감이 필수입니다.'},{tag:'cream',polarity:'like',quote:'쌀과 크림감이 필수입니다.'},{tag:'rice',polarity:'required',quote:'쌀과 크림감이 필수입니다.'}]};
const proposal={kind:'return',localMenu:'',reason:'쌀 풍미를 다시 만나고 싶어요.',keep:'구수한 쌀 맛',change:'단맛은 줄여도 좋아요.'};
test('HTTP 회원, 게시, 투표, 권한 통합',async t=>{
 const app=createApp({dbPath:':memory:',aiOverride:{configured:true,model:'test-only',taste:async()=>({result:taste,meta:{model:'test-only',ms:1}}),summary:async posts=>({result:{groups:[{label:'쌀 풍미',evidence:[{id:posts[0].id,quote:'쌀'}]}],caution:'시험'},meta:{model:'test-only',ms:1}})}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 async function req(route,body,cookie='',extra={}){const res=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json','X-Next-Cup':'1',Origin:base}),Cookie:cookie,...extra},body:body===undefined?undefined:JSON.stringify(body)});return{status:res.status,body:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};}
 let alice,bob,admin,id;const code=app.store.invite(),bobCode=app.store.invite(),adminCode=app.store.invite('admin');const password='synthetic-test-password-only';
 try{
 await t.test('비회원은 게시 목록 불가',async()=>assert.equal((await req('/api/posts')).status,401));
 await t.test('외부 Origin과 헤더 누락 차단',async()=>{assert.equal((await req('/api/auth/signup',{},'',{Origin:'https://example.com'})).status,403);assert.equal((await req('/api/auth/signup',{},'',{'X-Next-Cup':''})).status,403);});
 await t.test('짧은 비밀번호 차단',async()=>assert.equal((await req('/api/auth/signup',{handle:'alice',password:'short',invite:code})).status,400));
 await t.test('초대 가입과 쿠키',async()=>{alice=await req('/api/auth/signup',{handle:'alice',password,invite:code});assert.equal(alice.status,200);assert.ok(alice.cookie);assert.equal(alice.body.user.role,'member');});
 await t.test('초대 재사용 거절',async()=>assert.equal((await req('/api/auth/signup',{handle:'reuse',password,invite:code})).status,400));
 await t.test('다른 회원과 운영자 가입',async()=>{bob=await req('/api/auth/signup',{handle:'bob',password,invite:bobCode});admin=await req('/api/auth/signup',{handle:'owner',password,invite:adminCode});assert.equal(bob.status,200);assert.equal(admin.body.user.role,'admin');});
 await t.test('비밀번호 평문 미저장',()=>assert.notEqual(app.store.db.prepare('SELECT password FROM users WHERE handle=?').get('alice').password,password));
 await t.test('잘못된 로그인 거절',async()=>assert.equal((await req('/api/auth/login',{handle:'alice',password:'wrong-password'})).status,401));
 await t.test('동의 없는 게시 거절',async()=>assert.equal((await req('/api/posts',{type:'request',payload:proposal},alice.cookie)).status,400));
 await t.test('개인정보 패턴 게시 차단',async()=>assert.equal((await req('/api/posts',{type:'request',payload:{...proposal,reason:'test@example.com'},consent:true},alice.cookie)).status,400));
 await t.test('실제 저장과 목록 읽기',async()=>{const r=await req('/api/posts',{type:'request',payload:proposal,consent:true},alice.cookie);assert.equal(r.status,201);id=r.body.id;const rows=(await req('/api/posts',undefined,bob.cookie)).body.posts;assert.equal(rows.length,1);assert.equal(rows[0].mine,false);});
 await t.test('타인의 게시물 수정 거절',async()=>assert.equal((await req('/api/posts/'+id+'/edit',{payload:proposal,version:1,consent:true},bob.cookie)).status,403));
 await t.test('작성자 수정과 오래된 버전 충돌',async()=>{assert.equal((await req('/api/posts/'+id+'/edit',{payload:{...proposal,keep:'이천 쌀'},version:1,consent:true},alice.cookie)).status,200);assert.equal((await req('/api/posts/'+id+'/edit',{payload:proposal,version:1,consent:true},alice.cookie)).status,409);});
 await t.test('같은 표를 반복해도 한 표',async()=>{await Promise.all([1,2,3].map(()=>req('/api/posts/'+id+'/vote',{reason:'original'},bob.cookie)));assert.equal((await req('/api/posts',undefined,bob.cookie)).body.posts[0].votes[0].n,1);});
 await t.test('이유 변경과 취소',async()=>{await req('/api/posts/'+id+'/vote',{reason:'lessSweet'},bob.cookie);let rows=(await req('/api/posts',undefined,bob.cookie)).body.posts;assert.equal(rows[0].myVote,'lessSweet');assert.equal(rows[0].votes.reduce((n,v)=>n+v.n,0),1);await req('/api/posts/'+id+'/vote',{reason:null},bob.cookie);assert.equal((await req('/api/posts',undefined,bob.cookie)).body.posts[0].votes.length,0);});
 await t.test('신고 저장과 중복 방지',async()=>{await req('/api/posts/'+id+'/report',{reason:'misleading'},bob.cookie);await req('/api/posts/'+id+'/report',{reason:'personal'},bob.cookie);assert.equal(app.store.operations().reports,1);});
 await t.test('운영 화면 권한',async()=>{assert.equal((await req('/api/ops',undefined,bob.cookie)).status,403);assert.equal((await req('/api/ops',undefined,admin.cookie)).status,200);});
 await t.test('운영자 숨김, 복구 및 숨긴 글 투표 차단',async()=>{await req('/api/posts/'+id+'/visibility',{status:'hidden'},admin.cookie);assert.equal((await req('/api/posts',undefined,bob.cookie)).body.posts.length,0);assert.equal((await req('/api/posts/'+id+'/vote',{reason:'original'},bob.cookie)).status,404);assert.equal((await req('/api/posts/'+id+'/visibility',{status:'visible'},alice.cookie)).status,403);await req('/api/posts/'+id+'/visibility',{status:'visible'},admin.cookie);});
 await t.test('취향 API 전송 동의 필수',async()=>{assert.equal((await req('/api/ai/taste',{history:[{role:'user',text:'쌀 맛'}]})).status,400);assert.equal((await req('/api/ai/taste',{history:[{role:'user',text:'쌀 맛'}],consent:true})).status,200);});
 await t.test('요약 API 근거와 표본 건수',async()=>{const r=await req('/api/ai/summary',{consent:true},alice.cookie);assert.equal(r.status,200);assert.equal(r.body.sourceCount,1);assert.equal(r.body.result.groups[0].evidence[0].id,id);});
 await t.test('조건 검사와 출처',async()=>{const r=await req('/api/recommend',{tags:['cream'],essential:false,store:'all',dislikes:['ice']});assert.equal(r.status,200);assert.ok(!r.body.candidates.some(d=>d.id==='chocolate'));assert.equal(r.body.trace.length,4);});
 await t.test('비선호 겹침은 잘못된 입력',async()=>assert.equal((await req('/api/recommend',{tags:['cream'],dislikes:['cream'],essential:false,store:'all'})).status,400));
 await t.test('비공개 전환 및 빈 자료 요약 차단',async()=>{await req('/api/posts/'+id+'/visibility',{status:'withdrawn'},alice.cookie);assert.equal((await req('/api/posts',undefined,bob.cookie)).body.posts.length,0);assert.equal((await req('/api/ai/summary',{consent:true},bob.cookie)).status,400);});
 await t.test('로그아웃 세션 폐기',async()=>{await req('/api/auth/logout',{},alice.cookie);assert.equal((await req('/api/posts',undefined,alice.cookie)).status,401);});
 await t.test('키와 DB 파일 제공 안 함',async()=>{for(const route of ['/.env','/runtime/next-cup.sqlite','/ai.cjs'])assert.equal((await req(route)).status,404);});
 }finally{await app.close();}
});
test('AI 출력 검사',()=>{assert.ok(checkTaste(taste));assert.ok(!checkTaste({...taste,dislikes:['rice']}));assert.ok(!checkTaste({...taste,likes:['magic']}));const posts=[{id:'a',text:'구수한 쌀 맛이 좋아요'}];assert.ok(checkSummary({groups:[{label:'쌀',evidence:[{id:'a',quote:'쌀 맛'}]}],caution:''},posts));assert.ok(!checkSummary({groups:[{label:'쌀',evidence:[{id:'a',quote:'인기 폭발'}]}],caution:''},posts));assert.ok(!checkSummary({groups:[{label:'쌀',evidence:[{id:'other',quote:'쌀 맛'}]}],caution:''},posts));assert.ok(pii('연락처 test@example.com'));});
test('Gemini 실제 호출 없이 오류 경로 검사',async t=>{const config={key:'synthetic-not-real',model:'gemini-2.5-flash'};await t.test('정상 JSON',async()=>{const ai=createAI({config,fetchImpl:async()=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify(taste)}]}}]})})});assert.deepEqual((await ai.taste([{role:'user',text:'쌀과 크림감이 필수입니다.'}])).result,taste);});await t.test('잘못된 응답은 적용하지 않음',async()=>{const ai=createAI({config,fetchImpl:async()=>({ok:true,json:async()=>({candidates:[]})})});await assert.rejects(ai.taste([]),e=>e.code==='INVALID');});await t.test('한도 오류',async()=>{const ai=createAI({config,fetchImpl:async()=>({ok:false,status:429})});await assert.rejects(ai.taste([]),e=>e.code==='QUOTA');});await t.test('시간 초과',async()=>{const ai=createAI({config,fetchImpl:async()=>{throw Object.assign(Error(),{name:'TimeoutError'});}});await assert.rejects(ai.taste([]),e=>e.code==='TIMEOUT');});await t.test('키 없으면 호출 안 함',async()=>{const ai=createAI({config:{key:'',model:config.model},fetchImpl:async()=>{throw Error('should not call');}});await assert.rejects(ai.taste([]),e=>e.code==='NO_KEY');});});
test('AI 호출 상한과 민감정보 없는 운영 기록',()=>{const {openStore}=require('../app/db.cjs');const s=openStore(':memory:');try{const id=s.beginCall('taste','test',1);s.endCall(id,'ok',50,{promptTokenCount:12,candidatesTokenCount:10});assert.throws(()=>s.beginCall('taste','test',1),e=>e.status===429);assert.equal(s.operations().calls[0].inputTokens,12);assert.equal(s.operations().calls[0].ok,1);}finally{s.close();}});
