const {chromium}=require('playwright');
const {createApp}=require('../app/server.cjs');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true});const app=createApp({dbPath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const page=await browser.newPage();const output='runtime/browser-'+Date.now();fs.mkdirSync(output,{recursive:true});const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const check=(name,v)=>{assert.ok(v,name);checks.push(name)};try{
const baseURL=`http://127.0.0.1:${app.server.address().port}`;
await page.route('**/*',route=>new URL(route.request().url()).origin===baseURL?route.continue():route.abort());
await page.goto(baseURL+'/#community');
check('기존 커뮤니티 주소는 시작 화면',await page.locator('#start').isVisible());
check('계정과 시험 양식 없음',await page.locator('input[type=password],#trial-setup,#login-form').count()===0);
await page.locator('#hero-begin').click();check('첫 화면 버튼에서 입력으로 이동',await page.locator('#memory').evaluate(el=>document.activeElement===el));await page.locator('#manual').click();await page.locator('[name=like][value=ice]').check();await page.locator('#rice').selectOption('no');await page.locator('#priority').selectOption('ice');await page.locator('#taste-form button').click();await page.locator('.drink').first().waitFor();check('갈린 질감 필수 후보',await page.locator('.drink').count()===3);
await page.screenshot({path:output+'/portfolio-result.png',fullPage:true});await page.locator('[data-go=confirm]').click();await page.locator('#dislikes').locator('..').locator('summary').click();await page.locator('[name=avoid][value=cocoa]').check();await page.locator('#taste-form button').click();await page.locator('.drink').first().waitFor();check('초콜릿 제외 후 과일 후보 유지',await page.locator('.drink').count()===2);await page.locator('[data-go=confirm]').click();await page.locator('[name=avoid][value=fruit]').check();await page.locator('#taste-form button').click();await page.waitForFunction(()=>document.querySelector('#result-title').textContent.includes('찾지 못'));check('모순 없는 추천 보류',await page.locator('.drink').count()===0);
await page.locator('#to-request').click();await page.locator('#unmet').fill('가상 시험: 쌀의 구수함 <script>');await page.locator('#request-form button').click();await page.locator('.record').waitFor();await page.reload();check('가입 없이 저장 유지와 문자 처리',(await page.locator('.record').innerText()).includes('<script>'));
await page.locator('[data-go=start]:visible').click();await page.locator('#memory').fill('가상 입력');await page.locator('#consent').check();await page.route('**/api/ai/taste',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'가상 장애'})}));await page.locator('#interpret').click();await page.waitForFunction(()=>document.querySelector('#ai-status').textContent.includes('가상 장애'));check('AI 장애에도 입력 보존',await page.locator('#memory').inputValue()==='가상 입력');
await page.unroute('**/api/ai/taste');await page.route('**/api/ai/taste',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({result:{likes:['ice'],dislikes:['cocoa'],essentialRice:'unknown',understanding:'가상 AI 응답'}})}));await page.locator('#interpret').click();await page.locator('#confirm').waitFor({state:'visible'});check('AI 해석 확인과 쌀 미확인 유지',await page.locator('[name=like][value=ice]').isChecked()&&await page.locator('#rice').inputValue()==='');
for(const width of [375,812,1440]){await page.setViewportSize({width,height:900});check('가로 넘침 없음 '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
await page.locator('[data-go=start]:visible').click();await page.setViewportSize({width:1280,height:900});await page.screenshot({path:output+'/simple-desktop.png',fullPage:true});await page.setViewportSize({width:375,height:812});await page.emulateMedia({reducedMotion:'reduce'});await page.screenshot({path:output+'/simple-mobile.png',fullPage:true});check('화면 가운데점 없음',!/[·•‧ㆍ]/.test(await page.locator('body').innerText()));check('자바스크립트 오류 없음',!errors.length);fs.writeFileSync(output+'/simple-results.json',JSON.stringify({checks,errors,realAICalls:0,externalParticipants:0,kind:'synthetic-browser-test'},null,2));console.log(JSON.stringify({passed:checks.length,checks}));
}finally{await browser.close();app.server.closeAllConnections();await app.close();}})().catch(e=>{console.error(e);process.exitCode=1});
