'use strict';
const {DatabaseSync}=require('node:sqlite');const {randomBytes,createHash,scryptSync,timingSafeEqual,randomUUID}=require('node:crypto');
const hash=s=>createHash('sha256').update(s).digest('hex');
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
function openStore(file){
 const db=new DatabaseSync(file);db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,handle TEXT UNIQUE NOT NULL,password TEXT NOT NULL,salt TEXT NOT NULL,role TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS invites(token TEXT PRIMARY KEY,role TEXT NOT NULL,expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS posts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),type TEXT NOT NULL,payload TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'visible',created TEXT NOT NULL,updated TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS votes(post_id TEXT NOT NULL REFERENCES posts(id),user_id TEXT NOT NULL REFERENCES users(id),reason TEXT NOT NULL,PRIMARY KEY(post_id,user_id));
 CREATE TABLE IF NOT EXISTS reports(post_id TEXT NOT NULL REFERENCES posts(id),user_id TEXT NOT NULL REFERENCES users(id),reason TEXT NOT NULL,created TEXT NOT NULL,PRIMARY KEY(post_id,user_id));
 CREATE TABLE IF NOT EXISTS calls(id TEXT PRIMARY KEY,task TEXT NOT NULL,model TEXT NOT NULL,started INTEGER NOT NULL,ms INTEGER,status TEXT NOT NULL,input_tokens INTEGER DEFAULT 0,output_tokens INTEGER DEFAULT 0);
 CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,actor TEXT NOT NULL,post_id TEXT NOT NULL,action TEXT NOT NULL,created TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS crm_subscriptions(client_hash TEXT NOT NULL,topic TEXT NOT NULL,active INTEGER NOT NULL,created TEXT NOT NULL,updated TEXT NOT NULL,PRIMARY KEY(client_hash,topic));
 CREATE TABLE IF NOT EXISTS crm_deliveries(id TEXT PRIMARY KEY,client_hash TEXT NOT NULL,topic TEXT NOT NULL,event_id TEXT NOT NULL,status TEXT NOT NULL,created TEXT NOT NULL,UNIQUE(client_hash,event_id));`);
 const stmt=s=>db.prepare(s);const tx=fn=>{db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}};
 function invite(role='member'){const token=randomBytes(18).toString('base64url');stmt('INSERT INTO invites(token,role,expires) VALUES(?,?,?)').run(hash(token),role,Date.now()+7*86400000);return token;}
 function signup({handle,password,invite:code}){
  if(typeof handle!=='string'||!/^[a-zA-Z0-9_-]{3,24}$/.test(handle)||typeof password!=='string'||password.length<12||password.length>128||typeof code!=='string'||code.length>100)fail(400,'아이디는 영문, 숫자 3~24자, 비밀번호는 12~128자, 유효한 초대 코드가 필요합니다.');
  const salt=randomBytes(16).toString('hex'),pass=scryptSync(password,salt,64).toString('hex');
  return tx(()=>{const inv=stmt('SELECT * FROM invites WHERE token=? AND used=0 AND expires>?').get(hash(code),Date.now());if(!inv)fail(400,'초대 코드가 유효하지 않거나 이미 사용됐습니다.');if(stmt('SELECT id FROM users WHERE handle=?').get(handle.toLowerCase()))fail(409,'이미 사용 중인 아이디입니다.');const u={id:randomUUID(),handle:handle.toLowerCase(),role:inv.role};stmt('INSERT INTO users VALUES(?,?,?,?,?)').run(u.id,u.handle,pass,salt,u.role);stmt('UPDATE invites SET used=1 WHERE token=?').run(hash(code));return u;});
 }
 function login({handle,password}){if(typeof handle!=='string'||typeof password!=='string'||password.length>128)fail(401,'아이디 또는 비밀번호를 확인해 주세요.');const u=stmt('SELECT * FROM users WHERE handle=?').get(handle.toLowerCase());const calculated=scryptSync(password,u?.salt||'dummy-salt-for-timing',64);if(!u||!timingSafeEqual(calculated,Buffer.from(u.password,'hex')))fail(401,'아이디 또는 비밀번호를 확인해 주세요.');return{id:u.id,handle:u.handle,role:u.role};}
 function session(u){const token=randomBytes(32).toString('base64url');stmt('DELETE FROM sessions WHERE expires<?').run(Date.now());stmt('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),u.id,Date.now()+12*3600000);return token;}
 function user(token){if(typeof token!=='string'||token.length>100)return null;return stmt('SELECT u.id,u.handle,u.role FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.token=? AND s.expires>?').get(hash(token),Date.now())||null;}
 function list(u){return stmt("SELECT p.*,u.handle FROM posts p JOIN users u ON p.user_id=u.id WHERE p.status='visible' OR p.user_id=? OR ?='admin' ORDER BY p.created DESC LIMIT 100").all(u.id,u.role).map(p=>({...p,payload:JSON.parse(p.payload),mine:p.user_id===u.id,votes:stmt('SELECT reason,COUNT(*) AS n FROM votes WHERE post_id=? GROUP BY reason').all(p.id),myVote:stmt('SELECT reason FROM votes WHERE post_id=? AND user_id=?').get(p.id,u.id)?.reason||null,reports:u.role==='admin'?stmt('SELECT reason,created FROM reports WHERE post_id=?').all(p.id):undefined,user_id:undefined}));}
 function post(id){return stmt('SELECT * FROM posts WHERE id=?').get(id);}
 function create(u,type,payload){if(stmt('SELECT COUNT(*) n FROM posts WHERE user_id=?').get(u.id).n>=50)fail(429,'시험 운영에서는 계정당 제안 50건까지 저장합니다.');const id=randomUUID(),now=new Date().toISOString();stmt('INSERT INTO posts(id,user_id,type,payload,created,updated) VALUES(?,?,?,?,?,?)').run(id,u.id,type,JSON.stringify(payload),now,now);return id;}
 function edit(u,id,version,payload){const p=post(id);if(!p)fail(404,'제안을 찾을 수 없습니다.');if(p.user_id!==u.id)fail(403,'본인의 제안만 수정할 수 있습니다.');if(p.status==='hidden')fail(403,'운영자가 숨긴 제안은 수정할 수 없습니다.');const r=stmt('UPDATE posts SET payload=?,version=version+1,updated=? WHERE id=? AND version=?').run(JSON.stringify(payload),new Date().toISOString(),id,version);if(!r.changes)fail(409,'다른 화면에서 수정됐습니다. 목록을 새로 불러온 뒤 다시 작성해 주세요.');}
 function visibility(u,id,status){const p=post(id);if(!p)fail(404,'제안을 찾을 수 없습니다.');if(u.role!=='admin'&&(p.user_id!==u.id||p.status==='hidden'||!['visible','withdrawn'].includes(status)))fail(403,'변경 권한이 없습니다.');if(!['visible','withdrawn','hidden'].includes(status))fail(400,'표시 상태를 확인해 주세요.');tx(()=>{stmt('UPDATE posts SET status=?,version=version+1,updated=? WHERE id=?').run(status,new Date().toISOString(),id);stmt('INSERT INTO audit(actor,post_id,action,created) VALUES(?,?,?,?)').run(u.id,id,status,new Date().toISOString());});}
 function vote(u,id,reason){if(!['original','lessSweet','newIdea',null].includes(reason))fail(400,'투표 이유를 선택해 주세요.');const p=post(id);if(!p||p.status!=='visible')fail(404,'투표 가능한 제안이 아닙니다.');if(reason===null)stmt('DELETE FROM votes WHERE post_id=? AND user_id=?').run(id,u.id);else stmt('INSERT INTO votes VALUES(?,?,?) ON CONFLICT(post_id,user_id) DO UPDATE SET reason=excluded.reason').run(id,u.id,reason);}
 function report(u,id,reason){if(!post(id))fail(404,'제안을 찾을 수 없습니다.');if(!['personal','abuse','misleading'].includes(reason))fail(400,'신고 이유를 선택해 주세요.');stmt('INSERT INTO reports VALUES(?,?,?,?) ON CONFLICT(post_id,user_id) DO UPDATE SET reason=excluded.reason,created=excluded.created').run(id,u.id,reason,new Date().toISOString());}
 function beginCall(task,model,limit=40){return tx(()=>{if(stmt('SELECT COUNT(*) n FROM calls WHERE started>?').get(Date.now()-86400000).n>=limit)fail(429,'최근 24시간 AI 호출 한도에 도달했습니다. 수동 선택을 이용해 주세요.');const id=randomUUID();stmt('INSERT INTO calls(id,task,model,started,status) VALUES(?,?,?,?,?)').run(id,task,model,Date.now(),'running');return id;});}
 function endCall(id,status,ms,usage={}){const count=n=>Number.isFinite(n)&&n>=0?Math.floor(n):0;stmt('UPDATE calls SET status=?,ms=?,input_tokens=?,output_tokens=? WHERE id=?').run(status,ms,count(usage.promptTokenCount),count(usage.candidatesTokenCount)+count(usage.thoughtsTokenCount),id);}
 function operations(){return{calls:stmt('SELECT task,model,COUNT(*) count,SUM(status=\'ok\') ok,ROUND(AVG(ms)) avgMs,SUM(input_tokens) inputTokens,SUM(output_tokens) outputTokens FROM calls GROUP BY task,model').all(),reports:stmt('SELECT COUNT(*) count FROM reports').get().count};}
 function crmSubscribe(clientId,topics){const client=hash(clientId),now=new Date().toISOString();tx(()=>{stmt('UPDATE crm_subscriptions SET active=0,updated=? WHERE client_hash=?').run(now,client);for(const topic of topics)stmt('INSERT INTO crm_subscriptions VALUES(?,?,?,?,?) ON CONFLICT(client_hash,topic) DO UPDATE SET active=1,updated=excluded.updated').run(client,topic,1,now,now);});}
 function crmStatus(clientId){return stmt('SELECT topic FROM crm_subscriptions WHERE client_hash=? AND active=1 ORDER BY topic').all(hash(clientId)).map(x=>x.topic);}
 function crmUnsubscribe(clientId){stmt('UPDATE crm_subscriptions SET active=0,updated=? WHERE client_hash=?').run(new Date().toISOString(),hash(clientId));}
 function crmDeliver(clientId,event){const client=hash(clientId),now=new Date().toISOString(),id=randomUUID();try{stmt('INSERT INTO crm_deliveries VALUES(?,?,?,?,?,?)').run(id,client,event.topic,event.id,'browser_requested',now);return{status:'browser_requested',duplicate:false,created:now};}catch(error){if(String(error.message).includes('UNIQUE'))return{status:'already_requested',duplicate:true,created:stmt('SELECT created FROM crm_deliveries WHERE client_hash=? AND event_id=?').get(client,event.id).created};throw error;}}
 function crmMetrics(){return{subscribedClients:stmt('SELECT COUNT(DISTINCT client_hash) count FROM crm_subscriptions WHERE active=1').get().count,deliveryRequests:stmt('SELECT COUNT(*) count FROM crm_deliveries').get().count};}
 return{db,invite,signup,login,session,user,list,post,create,edit,visibility,vote,report,beginCall,endCall,operations,crmSubscribe,crmStatus,crmUnsubscribe,crmDeliver,crmMetrics,logout:t=>stmt('DELETE FROM sessions WHERE token=?').run(hash(t||'')),close:()=>db.close()};
}
module.exports={openStore,fail};
